name: 'dbt_project'
version: '1.0.0'
config-version: 2

# El "profile" debe coincidir con el nombre que pusimos en profiles.yml
profile: 'dbt_project'

# Definimos dónde están las carpetas
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración de los modelos (opcional, pero útil)
models:
  dbt_project:
    staging:
      +schema: bronze
    intermediate:
      +schema: silver
    marts:
      materialized: table
      +schema: gold